remote_theme: JJPPeters/jekyll-graphene-theme

# setup
title: CIF2XYZ # this is the main title in the header
tagline: Convert .cif files to .xyz # this is the text that appears next to the title
baseurl: /CIF2XYZ # the subpath of your site, e.g. /blog
url: https://jjppeters.github.io/CIF2XYZ/ # the base hostname & protocol for your site, e.g. http://example.com
repository: JJPPeters/CIF2XYZ

# contact
author:
  name: J. J. P. Peters
  github_username: JJPPeters
  url: https://github.com/JJPPeters
  email: jonathanjppeters@gmail.com